dingo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('maths/', include('maths.urls')),
    path('greetings/', include('greetings.urls')),
    path('sessions/', include("sessions.urls")),
    path('posts/', include("posts.urls")),
]

maths/urls.py
from django.urls import path
from maths.views import math, add, sub, mul, div, maths_list, math_details, results_list, maths_search
app_name = "maths"
urlpatterns = [
    path('', math),
    path('add/<int:a>/<int:b>', add),
    path('sub/<int:a>/<int:b>', sub),
    path('mul/<int:a>/<int:b>', mul),
    path('div/<int:a>/<int:b>', div),
    path('histories/', maths_list, name="list"),
    path('histories/<int:id>', math_details, name="details"),
    path('results/', results_list, name="results"),
    path('search/', maths_search, name="search"),
]

maths/models.py
from django.db import models

# Create your models here.

OPERATION_CHOICES = [
    ("add", "add"),
    ("sub", "sub"),
    ("mul", "mul"),
    ("div", "div"),
]


class Math(models.Model):
    operation = models.CharField(max_length=5, choices=OPERATION_CHOICES)
    a = models.IntegerField()
    b = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    result = models.ForeignKey(
        'maths.Result',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    def __str__(self):
        return f"id:{self.id}, a={self.a}, b={self.b}, operation={self.operation}"

    class Meta:
        ordering = ['id']


class Result(models.Model):
    value = models.FloatField(blank=True, null=True, unique=True)
    error = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        unique=True
    )

    def __str__(self):
        return f"value: {self.value} | error: {self.error}"

maths/forms.py
from django import forms
from maths.models import Result

OPERATION_CHOICES = [
    ("add", "add"),
    ("sub", "sub"),
    ("mul", "mul"),
    ("div", "div"),
]


class ResultForm(forms.ModelForm):
    class Meta:
        model = Result
        fields = "__all__"

    def clean(self):
        cleaned_data = super().clean()
        value = cleaned_data.get('value')
        error = cleaned_data.get('error')

        if value and error:
            raise forms.ValidationError("Podaj tylko jedną z wartości")
        elif not (value or error):
            raise forms.ValidationError("Nie podano żadnej wartości!")


class SearchForm(forms.Form):
    operation = forms.ChoiceField(label='Operacja', choices=OPERATION_CHOICES)

maths/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib import messages
from maths.models import Math, Result
from maths.forms import ResultForm, SearchForm
from django.core.paginator import Paginator


# Create your views here.

def math(request):
    return HttpResponse('Tu będzie matma')


def add(request, a, b):
    wynik = a + b
    c = {'a': a, 'b': b, 'operacja': '+', 'wynik': wynik}
    result = Result.objects.get_or_create(value=wynik)[0]
    Math.objects.create(operation='add', a=a, b=b, result=result)
    return render(
        request=request,
        template_name="maths/operation.html",
        context=c
    )


def sub(request, a, b):
    wynik = a - b
    c = {'a': a, 'b': b, 'operacja': '-', 'wynik': wynik}
    result = Result.objects.get_or_create(value=wynik)[0]
    Math.objects.create(operation='sub', a=a, b=b, result=result)
    return render(
        request=request,
        template_name="maths/operation.html",
        context=c
    )


def mul(request, a, b):
    wynik = a * b
    c = {'a': a, 'b': b, 'operacja': '*', 'wynik': wynik}
    result = Result.objects.get_or_create(value=wynik)[0]
    Math.objects.create(operation='mul', a=a, b=b, result=result)
    return render(
        request=request,
        template_name="maths/operation.html",
        context=c
    )


def div(request, a, b):
    if int(b) == 0:
        wynik = 'Error'
        messages.add_message(request, messages.ERROR, 'Dzielenie przez zero!')
    else:
        wynik = a / b
    c = {'a': a, 'b': b, 'operacja': '/', 'wynik': wynik}
    result = Result.objects.get_or_create(value=wynik)[0]
    Math.objects.create(operation='div', a=a, b=b, result=result)
    return render(
        request=request,
        template_name="maths/operation.html",
        context=c
    )


def maths_list(request):
    maths = Math.objects.all()
    paginator = Paginator(maths, 8)
    page_number = request.GET.get('page')
    maths = paginator.get_page(page_number)
    return render(
        request=request,
        template_name="maths/list.html",
        context={"maths": maths}
    )


def maths_search(request):
    operation = request.POST.get('operation')
    content = Math.objects.all().filter(operation=operation)
    form = SearchForm()
    return render(
        request=request,
        template_name="maths/search.html",
        context={
            "search_result": content,
            "form": form
        }
    )


def math_details(request, id):
    math = Math.objects.get(id=id)
    return render(
        request=request,
        template_name="maths/details.html",
        context={
            "math": math}
    )


def results_list(request):
    if request.method == "POST":
        form = ResultForm(request.POST)

        if form.is_valid():
            if form.cleaned_data['error'] == '':
                form.cleaned_data['error'] = None
            form.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                "Utworzono nowy Result!!"
            )
        else:
            messages.add_message(
                request,
                messages.ERROR,
                form.errors['__all__']
            )

    form = ResultForm()
    results = Result.objects.all()
    return render(
        request=request,
        template_name="maths/results.html",
        context={
            "results": results,
            "form": form
        }
    )

maths/templates/maths/details.html
{% extends "maths/main.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <table>
        <tr>
            <th>Operation</th>
            <td>{{ math.operation }}</td>
        </tr>
        <tr>
            <th>a</th>
            <td>{{ math.a }}</td>
        </tr>
        <tr>
            <th>b</th>
            <td>{{ math.b }}</td>
        </tr>
        <tr>
            <th>Created:</th>
            <td>{{ math.created }}</td>
        </tr>
        <tr>
            <th>Result</th>
            <td>{{ math.result }}</td>
        </tr>
    </table>
    <a href="{% url "maths:list" %}">back</a>
    {{ 'maths:list' }}
{% endblock %}

maths/templates/maths/list.html
{% extends "maths/main.html" %}

{% block title %}Moj tytuł{% endblock %}

{% block content %}
    <ul>
        {% for m in maths %}
            {# <li><a href="/maths/histories/{{ m.id }}">{{ m }}</a></li> #}
            <li><a href="{% url "maths:details" m.id %}">{{ m }}</a></li>
        {% endfor %}
    </ul>
    <div class="pagination">
        <span class="step-links">
           {% if maths.has_previous %}
               <a href="?page=1">« first</a>
               <a href="?page={{ maths.previous_page_number }}">previous</a>
           {% endif %}

           <span class="current">
               Page {{ maths.number }} of {{ maths.paginator.num_pages }}.
           </span>

           {% if maths.has_next %}
               <a href="?page={{ maths.next_page_number }}">next</a>
               <a href="?page={{ maths.paginator.num_pages }}">last »</a>
           {% endif %}
        </span>
    </div>
{% endblock content %}

maths/templates/maths/main.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Title{% endblock %}</title>
</head>
<body>
<div id="content">
    <div id="header">
        <b>To część stała szablonu głównego.</b>
    </div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <div id="inner-content">
        {% block content %}
            To jest blok kodu. Można go nadpisać w innych szablonach.
        {% endblock content %}
    </div>
</div>
</body>
</html>

maths/templates/maths/operation.html
{% extends 'maths/main.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    Wynik operacji {{ a }} {{ operacja }} {{ b }} wynosi {{ wynik }}
{% endblock %}

maths/templates/maths/results.html
{% extends "maths/main.html" %}

{% block title %}Maths list{% endblock %}

{% block content %}
    <ul>
        {% for r in results %}
            <li>{{ r }}</li>
        {% endfor %}
    </ul>

    <form method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" value="Wyślij>>">
    </form>

{% endblock %}

maths/templates/maths/search.html
{% extends "maths/main.html" %}

{% block title %}Moj tytuł{% endblock %}

{% block content %}
    <ul>
        {% for m in search_result %}
            <li>{{ m }}</li>
        {% endfor %}
    </ul>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Wyślij>>">
    </form>
{% endblock content %}