dingo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('maths/', include('maths.urls')),
    path('greetings/', include('greetings.urls')),
    path('sessions/', include("sessions.urls")),
    path('posts/', include("posts.urls")),
]

posts/urls.py
from django.urls import path
from posts.views import posts_list, post_details, author_details, author_list

app_name = "posts"
urlpatterns = [
    path('', posts_list, name="list"),
    path('<int:id>', post_details, name="details"),
    path('authors', author_list, name="a_list"),
    path('authors/<int:id>', author_details, name="a_details"),
]

posts/models.py
from django.db import models


# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    author_id = models.ForeignKey(
        'posts.Author',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    def __str__(self):
        return f"title: {self.title}, content: {self.content}, created: {self.created}, modified: {self.modified}," \
               f"author_id: {self.author_id}"


class Author(models.Model):
    nick = models.CharField(max_length=20, unique=True)
    email = models.EmailField(unique=True)
    bio = models.TextField(max_length=500, blank=True, null=True)

    def __str__(self):
        return f"nick: {self.nick}, email: {self.email}, bio: {self.bio}"

posts/forms.py
from django import forms
from posts.models import Author


class PostForm(forms.Form):
    title = forms.CharField(label='Tytuł', required=False)
    content = forms.CharField(label='Treść', widget=forms.Textarea, required=False)
    author_id = forms.ModelChoiceField(label='Wybierz autora', queryset=Author.objects.all(), initial=1, required=False)

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get('title')
        content = cleaned_data.get('content')
        author = cleaned_data.get('author_id')

        if not all([title, content, author]):
            raise forms.ValidationError("Musisz uzupełnić wszystkie wartości!")


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'

    def clean(self):
        cleaned_data = super().clean()
        nick = cleaned_data.get('nick')
        email = cleaned_data.get('email')

        if not (nick and email):
            raise forms.ValidationError("Musisz uzupełnić nick oraz email!")

posts/views.py
from django.shortcuts import render
from django.contrib import messages
from posts.models import Post, Author
from posts.forms import PostForm, AuthorForm


# Create your views here.

def posts_list(request):
    if request.method == "POST":
        form = PostForm(request.POST)

        if form.is_valid():
            Post.objects.get_or_create(**form.cleaned_data)
            messages.add_message(
                request,
                messages.SUCCESS,
                "Utworzono nowy post!"
            )
        else:
            messages.add_message(
                request,
                messages.ERROR,
                form.errors['__all__']
            )

    form = PostForm()
    posts = Post.objects.all()
    title = 'Posty'
    return render(
        request=request,
        template_name="posts/list.html",
        context={"posts": posts, "title": title, "form": form}
    )


def post_details(request, id):
    post = Post.objects.get(id=id)
    title = 'Detale postu'
    return render(
        request=request,
        template_name="posts/details.html",
        context={"post": post, 'title': title}
    )


def author_list(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)

        if form.is_valid():
            form.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                "Utworzono nowego autora!"
            )
        else:
            messages.add_message(
                request,
                messages.ERROR,
                form.errors['__all__']
            )

    form = AuthorForm()
    authors = Author.objects.all()
    title = 'Autorzy'
    return render(
        request=request,
        template_name="posts/author_list.html",
        context={"authors": authors, "title": title, "form": form}
    )


def author_details(request, id):
    author = Author.objects.get(id=id)
    title = 'Detale autora'
    return render(
        request=request,
        template_name="posts/author_details.html",
        context={"author": author, 'title': title}
    )

posts/templates/posts/author_details.html
{% extends "maths/main.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <table>
        <tr>
            <th>Nick:</th>
            <td>{{ author.nick }}</td>
        </tr>
        <tr>
            <th>E-mail:</th>
            <td>{{ author.email }}</td>
        </tr>
        <tr>
            <th>Bio:</th>
            <td>{{ author.bio }}</td>
        </tr>
    </table>
    <a href="{% url "posts:a_list" %}">Wróć do listy autorów</a>
{% endblock %}

posts/templates/posts/author_list.html
{% extends "maths/main.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <ul>
        {% for a in authors %}
            <li><a href="{% url "posts:a_details" a.id %}">{{ a.nick }}</a></li>
        {% endfor %}
    </ul>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Wyślij>>">
    </form>
{% endblock content %}

posts/templates/posts/details.html
{% extends "maths/main.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <table>
        <tr>
            <th>Tytuł:</th>
            <td>{{ post.title }}</td>
        </tr>
        <tr>
            <th>Treść:</th>
            <td>{{ post.content }}</td>
        </tr>
        <tr>
            <th>Wysłany:</th>
            <td>{{ post.created }}</td>
        </tr>
        <tr>
            <th>Zmodyfikowany:</th>
            <td>{{ post.modified }}</td>
        </tr>
        <tr>
            <th>Autor:</th>
            <td>{{ post.author_id.nick }}</td>
        </tr>
    </table>
    <a href="{% url "posts:list" %}">Wróć do listy postów</a>
{% endblock %}

posts/templates/posts/list.html
{% extends "maths/main.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <ul>
        {% for p in posts %}
            <li><a href="{% url "posts:details" p.id %}">{{ p.title }}</a></li>
        {% endfor %}
    </ul>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Wyślij>>">
    </form>
{% endblock content %}